---
- name: Create db_user
  community.postgresql.postgresql_db:
    name: "{{ ruby_postresql_db }}"
    owner: "{{ ruby_postresql_user }}"
  become: true
  become_user: "{{ ruby_postresql_root_user }}"