---
- name: Copy service file via template
  ansible.builtin.template:
    src: templates/app.service.j2
    dest: /etc/systemd/system/app.service
    owner: root
    group: root
    mode: 0664
  register: updatesystemd
  notify: restart_service
    

- name: systemd reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: updatesystemd.changed
  

- name: Enable and start app service
  ansible.builtin.systemd:
    name: app.service
    state: started
    enabled: true
    





 